# Site settings
title: Keep On Moving Forward
header-img: img/home-bg.png
email: bentonwong@gmail.com
copyright_name: bentonwong
description: > # this means to ignore newlines until "baseurl:"
  Learn New Things, Explore Opportunities, and Not Look Back
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bentonwong
learn_profile: bentonwong
email_username: bentonwong@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
